### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by jabbalaci** [cosminpopescu14/Life_After_Java8#1]
Thank you for the presentation, it was interesting. Some feedback:

* page 2: the images are too small, they are hard to read
* page 3: in the PDF, some Unicode characters (I guess) appear as squares. See the end of the last line. Check the PDF everywhere.
* page 11: ./MyProgram 1 2 3 -> ./MyProgram.java 1 2 3
* page 33: use a larger font

**Comment by cosminpopescu14** [comment]
please take a look :)
and thank you for the feedback.

**Comment by jabbalaci** [comment]
Nice :)

**Comment by cosminpopescu14** [comment]
I will close the issue. If there is something else that needs to be fixed, please open a new issue.
Thank you!
